services:
  - type: web
    name: report-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:api"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: report-db
          property: connectionString
      - key: EMAIL_USER
        value: your_email@example.com
      - key: EMAIL_PASS
        sync: false

databases:
  - name: report-db
    plan: free